server:
  port: 9003

eureka:
  instance:
    hostname: www.eureka03.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://www.eureka01.com:9001/eureka/,http://www.eureka02.com:9002/eureka/

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"