server:
  port: 8002

mybatis:
  config-location: classpath:config/mybatisconfig.xml   #
  type-aliases-package: com.api.bean
  mapper-locations: classpath:config/mapper/*.xml

spring:
  application:
    name: server-provider-01  # \u670D\u52A1\u5E94\u7528\u5B9E\u4F8B\u7684\u540D\u5B57 \u914D\u7F6E\u96C6\u7FA4\u65F6\u5FC5\u987B\u4E00\u81F4
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud02?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root


# \u6CE8\u518C\u670D\u52A1
eureka:
  client:
    service-url:
      defaultZone: http://www.eureka01.com:9001/eureka,http://www.eureka02.com:9002/eureka,http://www.eureka03.com:9003/eureka
  instance:
    instance-id: microservice-provider-8002
    prefer-ip-address: true     #\u8BBF\u95EE\u8DEF\u5F84\u53EF\u4EE5\u663E\u793AIP\u5730\u5740

