server:
  port: 4000

mybatis:
  config-location: classpath:config/mybatisconfig.xml   #
  type-aliases-package: com.api.bean
  mapper-locations: classpath:config/mapper/*.xml

spring:
  application:
    name: server-provider-01  # 服务应用实例的名字
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud03?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root


eureka:
  client:
    service-url:
      defaultZone: http://www.eureka01.com:9001/eureka,http://www.eureka02.com:9002/eureka,http://www.eureka03.com:9003/eureka
  instance:
    instance-id: microservice-provider-4000_hystrix
    prefer-ip-address: true
