

# \u5BA2\u6237\u7AEF
eureka:
  client:
    register-with-eureka: false  # \u5BA2\u6237\u7AEF\u81EA\u5DF1\u4E0D\u7528\u6CE8\u518C\u800C\u662F\u53BB\u6CE8\u518C\u4E2D\u5FC3\u53BB\u627E\u670D\u52A1
    service-url:
      defaultZone: http://www.eureka01.com:9001/eureka,http://www.eureka02.com:9002/eureka,http://www.eureka03.com:9003/eureka

server:
  port: 5000

# 测试feign中使用断路器hystrix 默认关闭，需要开启
feign:
  hystrix:
    enabled: true

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
